name: Update Packages & Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'


permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y skopeo jq

      - name: Checkout
        uses: actions/checkout@v4

      - name: install python dependencies
        run: |
          sudo pip install jinja2 python-hcl2
          sudo curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash
          sudo apt install task
      - name: Update Packages
        run: |
          sudo task update-packages
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "chore: update base image digests"
          branch: update-base-images
          title: "ðŸ˜¸ Update Packages & Images"
          body: "Automated update for images in versions.hcl"
          delete-branch: true
