name: Update Base Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'


permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y skopeo jq

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update versions.hcl
        run: |
          chmod +x get_latest.sh
          ./get_latest.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: "chore: update base image digests"
          branch: update-base-images
          title: "ðŸ¤– Update Base Image Digests"
          body: "Automated update for images in versions.hcl"
          delete-branch: true
